// Code generated by MockGen. DO NOT EDIT.
package starters

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStartersService is a mock of StartersService interface.
type MockStartersService struct {
	ctrl     *gomock.Controller
	recorder *MockStartersServiceMockRecorder
}

// MockStartersServiceMockRecorder is the mock recorder for MockStartersService.
type MockStartersServiceMockRecorder struct {
	mock *MockStartersService
}

// NewMockStartersService creates a new mock instance.
func NewMockStartersService(ctrl *gomock.Controller) *MockStartersService {
	mock := &MockStartersService{ctrl: ctrl}
	mock.recorder = &MockStartersServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStartersService) EXPECT() *MockStartersServiceMockRecorder {
	return m.recorder
}

// GetStarters mocks base method.
func (m *MockStartersService) GetStarters(ctx context.Context, input StartersInput) (*StartersOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStarters", ctx, input)
	ret0, _ := ret[0].(*StartersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStarters indicates an expected call of GetStarters.
func (mr *MockStartersServiceMockRecorder) GetStarters(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStarters", reflect.TypeOf((*MockStartersService)(nil).GetStarters), ctx, input)
}
