// Code generated by hand for MockGen compatibility. DO NOT EDIT manually unless the interface changes.
package flows

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// ContactHasOpenTicket mocks base method.
func (m *MockIClient) ContactHasOpenTicket(channelUUID string, contactURN string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContactHasOpenTicket", channelUUID, contactURN)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContactHasOpenTicket indicates an expected call of ContactHasOpenTicket.
func (mr *MockIClientMockRecorder) ContactHasOpenTicket(channelUUID, contactURN interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContactHasOpenTicket", reflect.TypeOf((*MockIClient)(nil).ContactHasOpenTicket), channelUUID, contactURN)
}

// GetChannelAllowedDomains mocks base method.
func (m *MockIClient) GetChannelAllowedDomains(channelUUID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelAllowedDomains", channelUUID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelAllowedDomains indicates an expected call of GetChannelAllowedDomains.
func (mr *MockIClientMockRecorder) GetChannelAllowedDomains(channelUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelAllowedDomains", reflect.TypeOf((*MockIClient)(nil).GetChannelAllowedDomains), channelUUID)
}

// GetChannelProjectLanguage mocks base method.
func (m *MockIClient) GetChannelProjectLanguage(channelUUID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelProjectLanguage", channelUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelProjectLanguage indicates an expected call of GetChannelProjectLanguage.
func (mr *MockIClientMockRecorder) GetChannelProjectLanguage(channelUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelProjectLanguage", reflect.TypeOf((*MockIClient)(nil).GetChannelProjectLanguage), channelUUID)
}

// UpdateContactFields mocks base method.
func (m *MockIClient) UpdateContactFields(channelUUID string, contactURN string, contactFields map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContactFields", channelUUID, contactURN, contactFields)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContactFields indicates an expected call of UpdateContactFields.
func (mr *MockIClientMockRecorder) UpdateContactFields(channelUUID, contactURN, contactFields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContactFields", reflect.TypeOf((*MockIClient)(nil).UpdateContactFields), channelUUID, contactURN, contactFields)
}

// GetElevenLabsAPIKey mocks base method.
func (m *MockIClient) GetElevenLabsAPIKey(channelUUID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetElevenLabsAPIKey", channelUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetElevenLabsAPIKey indicates an expected call of GetElevenLabsAPIKey.
func (mr *MockIClientMockRecorder) GetElevenLabsAPIKey(channelUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetElevenLabsAPIKey", reflect.TypeOf((*MockIClient)(nil).GetElevenLabsAPIKey), channelUUID)
}

// ResolvePSTNChannel mocks base method.
func (m *MockIClient) ResolvePSTNChannel(did string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolvePSTNChannel", did)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResolvePSTNChannel indicates an expected call of ResolvePSTNChannel.
func (mr *MockIClientMockRecorder) ResolvePSTNChannel(did interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolvePSTNChannel", reflect.TypeOf((*MockIClient)(nil).ResolvePSTNChannel), did)
}
