// Protocol Buffer definition for message streaming service
// Adapted from Nexus message streaming protocol

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/grpc/proto/message_stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamMessage - Main message for streaming from external services (Nexus)
type StreamMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                                                   // Message type: "setup", "delta", "completed", "control", etc.
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                                                                    // Unique message ID (groups delta chunks together)
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                                                             // Message content (text chunk for "delta", full text for "completed")
	ChannelUuid   string                 `protobuf:"bytes,4,opt,name=channel_uuid,json=channelUuid,proto3" json:"channel_uuid,omitempty"`                                                  // Channel UUID
	ContactUrn    string                 `protobuf:"bytes,5,opt,name=contact_urn,json=contactUrn,proto3" json:"contact_urn,omitempty"`                                                     // Contact URN (e.g., "whatsapp:+5511999999999")
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                         // Message timestamp
	ProjectUuid   string                 `protobuf:"bytes,8,opt,name=project_uuid,json=projectUuid,proto3" json:"project_uuid,omitempty"`                                                  // Project UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_pkg_grpc_proto_message_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_message_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_message_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StreamMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *StreamMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamMessage) GetChannelUuid() string {
	if x != nil {
		return x.ChannelUuid
	}
	return ""
}

func (x *StreamMessage) GetContactUrn() string {
	if x != nil {
		return x.ContactUrn
	}
	return ""
}

func (x *StreamMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StreamMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *StreamMessage) GetProjectUuid() string {
	if x != nil {
		return x.ProjectUuid
	}
	return ""
}

// StreamResponse - Response from this server to external service
type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                       // "success", "error", "processing", etc.
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                                                            // Message ID this response refers to
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                     // Response message
	Sequence      int32                  `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`                                                                  // Sequence number
	IsFinal       bool                   `protobuf:"varint,5,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`                                                     // Whether this is the last response
	ErrorCode     string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`                                                // Error code if status is "error"
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                       // Error details if status is "error"
	Data          map[string]string      `protobuf:"bytes,8,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional response data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_pkg_grpc_proto_message_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_message_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_message_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StreamResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *StreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamResponse) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StreamResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *StreamResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *StreamResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StreamResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

// SetupRequest - Initial setup message from external service
type SetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ChannelUuid   string                 `protobuf:"bytes,2,opt,name=channel_uuid,json=channelUuid,proto3" json:"channel_uuid,omitempty"`
	ContactUrn    string                 `protobuf:"bytes,3,opt,name=contact_urn,json=contactUrn,proto3" json:"contact_urn,omitempty"`
	ProjectUuid   string                 `protobuf:"bytes,4,opt,name=project_uuid,json=projectUuid,proto3" json:"project_uuid,omitempty"`
	Config        map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_pkg_grpc_proto_message_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_message_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_message_stream_proto_rawDescGZIP(), []int{2}
}

func (x *SetupRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SetupRequest) GetChannelUuid() string {
	if x != nil {
		return x.ChannelUuid
	}
	return ""
}

func (x *SetupRequest) GetContactUrn() string {
	if x != nil {
		return x.ContactUrn
	}
	return ""
}

func (x *SetupRequest) GetProjectUuid() string {
	if x != nil {
		return x.ProjectUuid
	}
	return ""
}

func (x *SetupRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// SetupResponse - Response to setup from this server
type SetupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupResponse) Reset() {
	*x = SetupResponse{}
	mi := &file_pkg_grpc_proto_message_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupResponse) ProtoMessage() {}

func (x *SetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_message_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupResponse.ProtoReflect.Descriptor instead.
func (*SetupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_message_stream_proto_rawDescGZIP(), []int{3}
}

func (x *SetupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetupResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetupResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pkg_grpc_proto_message_stream_proto protoreflect.FileDescriptor

const file_pkg_grpc_proto_message_stream_proto_rawDesc = "" +
	"\n" +
	"#pkg/grpc/proto/message_stream.proto\x12\x14nexus.message_stream\"\xe5\x02\n" +
	"\rStreamMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fchannel_uuid\x18\x04 \x01(\tR\vchannelUuid\x12\x1f\n" +
	"\vcontact_urn\x18\x05 \x01(\tR\n" +
	"contactUrn\x12M\n" +
	"\bmetadata\x18\x06 \x03(\v21.nexus.message_stream.StreamMessage.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12!\n" +
	"\fproject_uuid\x18\b \x01(\tR\vprojectUuid\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x02\n" +
	"\x0eStreamResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x05R\bsequence\x12\x19\n" +
	"\bis_final\x18\x05 \x01(\bR\aisFinal\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12B\n" +
	"\x04data\x18\b \x03(\v2..nexus.message_stream.StreamResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x02\n" +
	"\fSetupRequest\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12!\n" +
	"\fchannel_uuid\x18\x02 \x01(\tR\vchannelUuid\x12\x1f\n" +
	"\vcontact_urn\x18\x03 \x01(\tR\n" +
	"contactUrn\x12!\n" +
	"\fproject_uuid\x18\x04 \x01(\tR\vprojectUuid\x12F\n" +
	"\x06config\x18\x05 \x03(\v2..nexus.message_stream.SetupRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\rSetupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2\x82\x03\n" +
	"\x14MessageStreamService\x12P\n" +
	"\x05Setup\x12\".nexus.message_stream.SetupRequest\x1a#.nexus.message_stream.SetupResponse\x12_\n" +
	"\x0eStreamMessages\x12#.nexus.message_stream.StreamMessage\x1a$.nexus.message_stream.StreamResponse(\x010\x01\x12X\n" +
	"\vSendMessage\x12#.nexus.message_stream.StreamMessage\x1a$.nexus.message_stream.StreamResponse\x12]\n" +
	"\x0eStreamToServer\x12#.nexus.message_stream.StreamMessage\x1a$.nexus.message_stream.StreamResponse(\x01B)Z'github.com/ilhasoft/wwcs/pkg/grpc/protob\x06proto3"

var (
	file_pkg_grpc_proto_message_stream_proto_rawDescOnce sync.Once
	file_pkg_grpc_proto_message_stream_proto_rawDescData []byte
)

func file_pkg_grpc_proto_message_stream_proto_rawDescGZIP() []byte {
	file_pkg_grpc_proto_message_stream_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_proto_message_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_message_stream_proto_rawDesc), len(file_pkg_grpc_proto_message_stream_proto_rawDesc)))
	})
	return file_pkg_grpc_proto_message_stream_proto_rawDescData
}

var file_pkg_grpc_proto_message_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_grpc_proto_message_stream_proto_goTypes = []any{
	(*StreamMessage)(nil),  // 0: nexus.message_stream.StreamMessage
	(*StreamResponse)(nil), // 1: nexus.message_stream.StreamResponse
	(*SetupRequest)(nil),   // 2: nexus.message_stream.SetupRequest
	(*SetupResponse)(nil),  // 3: nexus.message_stream.SetupResponse
	nil,                    // 4: nexus.message_stream.StreamMessage.MetadataEntry
	nil,                    // 5: nexus.message_stream.StreamResponse.DataEntry
	nil,                    // 6: nexus.message_stream.SetupRequest.ConfigEntry
}
var file_pkg_grpc_proto_message_stream_proto_depIdxs = []int32{
	4, // 0: nexus.message_stream.StreamMessage.metadata:type_name -> nexus.message_stream.StreamMessage.MetadataEntry
	5, // 1: nexus.message_stream.StreamResponse.data:type_name -> nexus.message_stream.StreamResponse.DataEntry
	6, // 2: nexus.message_stream.SetupRequest.config:type_name -> nexus.message_stream.SetupRequest.ConfigEntry
	2, // 3: nexus.message_stream.MessageStreamService.Setup:input_type -> nexus.message_stream.SetupRequest
	0, // 4: nexus.message_stream.MessageStreamService.StreamMessages:input_type -> nexus.message_stream.StreamMessage
	0, // 5: nexus.message_stream.MessageStreamService.SendMessage:input_type -> nexus.message_stream.StreamMessage
	0, // 6: nexus.message_stream.MessageStreamService.StreamToServer:input_type -> nexus.message_stream.StreamMessage
	3, // 7: nexus.message_stream.MessageStreamService.Setup:output_type -> nexus.message_stream.SetupResponse
	1, // 8: nexus.message_stream.MessageStreamService.StreamMessages:output_type -> nexus.message_stream.StreamResponse
	1, // 9: nexus.message_stream.MessageStreamService.SendMessage:output_type -> nexus.message_stream.StreamResponse
	1, // 10: nexus.message_stream.MessageStreamService.StreamToServer:output_type -> nexus.message_stream.StreamResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_grpc_proto_message_stream_proto_init() }
func file_pkg_grpc_proto_message_stream_proto_init() {
	if File_pkg_grpc_proto_message_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_message_stream_proto_rawDesc), len(file_pkg_grpc_proto_message_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_proto_message_stream_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_proto_message_stream_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_proto_message_stream_proto_msgTypes,
	}.Build()
	File_pkg_grpc_proto_message_stream_proto = out.File
	file_pkg_grpc_proto_message_stream_proto_goTypes = nil
	file_pkg_grpc_proto_message_stream_proto_depIdxs = nil
}
