// Protocol Buffer definition for message streaming service
// Adapted from Nexus message streaming protocol

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: pkg/grpc/proto/message_stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageStreamService_Setup_FullMethodName          = "/message_stream.MessageStreamService/Setup"
	MessageStreamService_StreamMessages_FullMethodName = "/message_stream.MessageStreamService/StreamMessages"
	MessageStreamService_SendMessage_FullMethodName    = "/message_stream.MessageStreamService/SendMessage"
	MessageStreamService_StreamToServer_FullMethodName = "/message_stream.MessageStreamService/StreamToServer"
)

// MessageStreamServiceClient is the client API for MessageStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MessageStreamService handles message streaming from external services (Nexus)
// This server receives streamed messages and forwards them to WebSocket clients
type MessageStreamServiceClient interface {
	// Setup - Initialize streaming session
	Setup(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*SetupResponse, error)
	// StreamMessages - Bidirectional streaming (main method for delta streaming)
	// External service sends StreamMessage chunks, server responds with acknowledgments
	StreamMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamResponse], error)
	// SendMessage - Single complete message (unary, for non-streaming messages)
	SendMessage(ctx context.Context, in *StreamMessage, opts ...grpc.CallOption) (*StreamResponse, error)
	// StreamToServer - Client streams messages, server responds once when complete
	StreamToServer(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamMessage, StreamResponse], error)
}

type messageStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageStreamServiceClient(cc grpc.ClientConnInterface) MessageStreamServiceClient {
	return &messageStreamServiceClient{cc}
}

func (c *messageStreamServiceClient) Setup(ctx context.Context, in *SetupRequest, opts ...grpc.CallOption) (*SetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupResponse)
	err := c.cc.Invoke(ctx, MessageStreamService_Setup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageStreamServiceClient) StreamMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamMessage, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageStreamService_ServiceDesc.Streams[0], MessageStreamService_StreamMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessage, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageStreamService_StreamMessagesClient = grpc.BidiStreamingClient[StreamMessage, StreamResponse]

func (c *messageStreamServiceClient) SendMessage(ctx context.Context, in *StreamMessage, opts ...grpc.CallOption) (*StreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamResponse)
	err := c.cc.Invoke(ctx, MessageStreamService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageStreamServiceClient) StreamToServer(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamMessage, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageStreamService_ServiceDesc.Streams[1], MessageStreamService_StreamToServer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMessage, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageStreamService_StreamToServerClient = grpc.ClientStreamingClient[StreamMessage, StreamResponse]

// MessageStreamServiceServer is the server API for MessageStreamService service.
// All implementations must embed UnimplementedMessageStreamServiceServer
// for forward compatibility.
//
// MessageStreamService handles message streaming from external services (Nexus)
// This server receives streamed messages and forwards them to WebSocket clients
type MessageStreamServiceServer interface {
	// Setup - Initialize streaming session
	Setup(context.Context, *SetupRequest) (*SetupResponse, error)
	// StreamMessages - Bidirectional streaming (main method for delta streaming)
	// External service sends StreamMessage chunks, server responds with acknowledgments
	StreamMessages(grpc.BidiStreamingServer[StreamMessage, StreamResponse]) error
	// SendMessage - Single complete message (unary, for non-streaming messages)
	SendMessage(context.Context, *StreamMessage) (*StreamResponse, error)
	// StreamToServer - Client streams messages, server responds once when complete
	StreamToServer(grpc.ClientStreamingServer[StreamMessage, StreamResponse]) error
	mustEmbedUnimplementedMessageStreamServiceServer()
}

// UnimplementedMessageStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageStreamServiceServer struct{}

func (UnimplementedMessageStreamServiceServer) Setup(context.Context, *SetupRequest) (*SetupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Setup not implemented")
}
func (UnimplementedMessageStreamServiceServer) StreamMessages(grpc.BidiStreamingServer[StreamMessage, StreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedMessageStreamServiceServer) SendMessage(context.Context, *StreamMessage) (*StreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageStreamServiceServer) StreamToServer(grpc.ClientStreamingServer[StreamMessage, StreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamToServer not implemented")
}
func (UnimplementedMessageStreamServiceServer) mustEmbedUnimplementedMessageStreamServiceServer() {}
func (UnimplementedMessageStreamServiceServer) testEmbeddedByValue()                              {}

// UnsafeMessageStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageStreamServiceServer will
// result in compilation errors.
type UnsafeMessageStreamServiceServer interface {
	mustEmbedUnimplementedMessageStreamServiceServer()
}

func RegisterMessageStreamServiceServer(s grpc.ServiceRegistrar, srv MessageStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedMessageStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageStreamService_ServiceDesc, srv)
}

func _MessageStreamService_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageStreamServiceServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageStreamService_Setup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageStreamServiceServer).Setup(ctx, req.(*SetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageStreamService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageStreamServiceServer).StreamMessages(&grpc.GenericServerStream[StreamMessage, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageStreamService_StreamMessagesServer = grpc.BidiStreamingServer[StreamMessage, StreamResponse]

func _MessageStreamService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageStreamServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageStreamService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageStreamServiceServer).SendMessage(ctx, req.(*StreamMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageStreamService_StreamToServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageStreamServiceServer).StreamToServer(&grpc.GenericServerStream[StreamMessage, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageStreamService_StreamToServerServer = grpc.ClientStreamingServer[StreamMessage, StreamResponse]

// MessageStreamService_ServiceDesc is the grpc.ServiceDesc for MessageStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message_stream.MessageStreamService",
	HandlerType: (*MessageStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Setup",
			Handler:    _MessageStreamService_Setup_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _MessageStreamService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _MessageStreamService_StreamMessages_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamToServer",
			Handler:       _MessageStreamService_StreamToServer_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/grpc/proto/message_stream.proto",
}
