// Code generated by MockGen. DO NOT EDIT.
package vtex

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// AddOrUpdateCartItem mocks base method.
func (m *MockIClient) AddOrUpdateCartItem(ctx context.Context, vtexAccount, orderFormID, itemID, seller string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrUpdateCartItem", ctx, vtexAccount, orderFormID, itemID, seller)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrUpdateCartItem indicates an expected call of AddOrUpdateCartItem.
func (mr *MockIClientMockRecorder) AddOrUpdateCartItem(ctx, vtexAccount, orderFormID, itemID, seller interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrUpdateCartItem", reflect.TypeOf((*MockIClient)(nil).AddOrUpdateCartItem), ctx, vtexAccount, orderFormID, itemID, seller)
}

// UpdateMarketingData mocks base method.
func (m *MockIClient) UpdateMarketingData(ctx context.Context, vtexAccount, orderFormID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMarketingData", ctx, vtexAccount, orderFormID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMarketingData indicates an expected call of UpdateMarketingData.
func (mr *MockIClientMockRecorder) UpdateMarketingData(ctx, vtexAccount, orderFormID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMarketingData", reflect.TypeOf((*MockIClient)(nil).UpdateMarketingData), ctx, vtexAccount, orderFormID)
}
